<pre> <h1>Pandas :</h1> is a python library which is used to analyze and manipulate the data, we can read and create datasers using pandas.
    pandas is of two type :
                            -->Series
                            --> DataFrame
     
</pre>

In [1]:
import pandas as pd

In [4]:
## Creating  a Series
# Convert list into Series

s = pd.Series(['a','b','c','d'])
s

0    a
1    b
2    c
3    d
dtype: object

In [5]:
type(s)

pandas.core.series.Series

In [6]:
s[2]

'c'

In [9]:
# Slicing 
s = pd.Series(['a','b','c','d'],index=[10,20,30,40])
s

10    a
20    b
30    c
40    d
dtype: object

In [11]:
# in slicing we can only use orignal index not the updated index
s[1:4:1]

20    b
30    c
40    d
dtype: object

In [12]:
# Tuple to Seies
t = pd.Series((100,200,300,400))
t

0    100
1    200
2    300
3    400
dtype: int64

In [13]:
# Set to series is not possible

In [15]:
# dictionary to Series
d = pd.Series({'a':1, 'b':2 , 'c':3, 'd':4, 'e':5})
d
# it treats the key as index value

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [16]:
d1 = pd.Series({'a':1, 'b':2 , 'c':3, 'd':4, 'e':5},index=['e','f','g','c','a'])
d1

e    5.0
f    NaN
g    NaN
c    3.0
a    1.0
dtype: float64

In [17]:
d['a']

np.int64(1)

In [24]:
## Creating  a DataFrame

d = { 'Name': ['ROHIT', 'MOHIT','RAM','PUROHIT','AMIT','HARI','RAJU'],
       'ROLL' : [20,21,22,23,24,25,26],
        'Course' : ['AI', 'Python', 'C', 'Java', 'C++', 'DA','WD']}
d

{'Name': ['ROHIT', 'MOHIT', 'RAM', 'PUROHIT', 'AMIT', 'HARI', 'RAJU'],
 'ROLL': [20, 21, 22, 23, 24, 25, 26],
 'Course': ['AI', 'Python', 'C', 'Java', 'C++', 'DA', 'WD']}

In [25]:
df = pd.DataFrame(d)
df

      Name  ROLL  Course
0    ROHIT    20      AI
1    MOHIT    21  Python
2      RAM    22       C
3  PUROHIT    23    Java
4     AMIT    24     C++
5     HARI    25      DA
6     RAJU    26      WD

In [27]:
type(df)

pandas.core.frame.DataFrame

In [29]:
df.Name

0      ROHIT
1      MOHIT
2        RAM
3    PUROHIT
4       AMIT
5       HARI
6       RAJU
Name: Name, dtype: object

In [30]:
df.iloc[::,::2]

      Name  Course
0    ROHIT      AI
1    MOHIT  Python
2      RAM       C
3  PUROHIT    Java
4     AMIT     C++
5     HARI      DA
6     RAJU      WD

In [31]:
df.iloc[::2,::]
## Even

    Name  ROLL Course
0  ROHIT    20     AI
2    RAM    22      C
4   AMIT    24    C++
6   RAJU    26     WD

In [32]:
df.iloc[1::2,::]
## odd

      Name  ROLL  Course
1    MOHIT    21  Python
3  PUROHIT    23    Java
5     HARI    25      DA

In [33]:
df.iloc[2]

Name      RAM
ROLL       22
Course      C
Name: 2, dtype: object

In [34]:
df.iloc[::,2]

0        AI
1    Python
2         C
3      Java
4       C++
5        DA
6        WD
Name: Course, dtype: object

In [35]:
df.head()

      Name  ROLL  Course
0    ROHIT    20      AI
1    MOHIT    21  Python
2      RAM    22       C
3  PUROHIT    23    Java
4     AMIT    24     C++

In [36]:
df.tail()

      Name  ROLL Course
2      RAM    22      C
3  PUROHIT    23   Java
4     AMIT    24    C++
5     HARI    25     DA
6     RAJU    26     WD

In [37]:
df.sample()

   Name  ROLL Course
6  RAJU    26     WD

In [38]:
## Renaming the column
df = df.rename(columns={'ROLL' : 'Roll_no'})
df

      Name  Roll_no  Course
0    ROHIT       20      AI
1    MOHIT       21  Python
2      RAM       22       C
3  PUROHIT       23    Java
4     AMIT       24     C++
5     HARI       25      DA
6     RAJU       26      WD

In [41]:
## 
df.set_index('Roll_no', inplace=True)
df

            Name  Course
Roll_no
20         ROHIT      AI
21         MOHIT  Python
22           RAM       C
23       PUROHIT    Java
24          AMIT     C++
25          HARI      DA
26          RAJU      WD

In [42]:
df.Course[23]

'Java'

In [40]:
df = df.reset_index()
df

   Roll_no     Name  Course
0       20    ROHIT      AI
1       21    MOHIT  Python
2       22      RAM       C
3       23  PUROHIT    Java
4       24     AMIT     C++
5       25     HARI      DA
6       26     RAJU      WD

In [46]:
df = pd.DataFrame({
     'Days' : [1,2,3,4,5,6],
     'Places':['Puri', 'Konark','BBSR','CTC', 'Rourkela', 'Kolkata'],
      'Visitors' : [6124,5600,4890,5000,5400,5500]})
df

   Days    Places  Visitors
0     1      Puri      6124
1     2    Konark      5600
2     3      BBSR      4890
3     4       CTC      5000
4     5  Rourkela      5400
5     6   Kolkata      5500

In [47]:
## To check missing Value
df.isnull()

    Days  Places  Visitors
0  False   False     False
1  False   False     False
2  False   False     False
3  False   False     False
4  False   False     False
5  False   False     False

In [48]:
df.isnull().sum()

Days        0
Places      0
Visitors    0
dtype: int64

In [73]:
import numpy as np
df = pd.DataFrame({
     'Days' : [1,2,3,4,5,6],
     'Places':['Puri', 'Konark','BBSR',np.nan, 'Rourkela', 'Kolkata'],
      'Visitors' : [6124,5600,4890,5000,5400,5500]})
df

   Days    Places  Visitors
0     1      Puri      6124
1     2    Konark      5600
2     3      BBSR      4890
3     4       NaN      5000
4     5  Rourkela      5400
5     6   Kolkata      5500

In [74]:
df.isnull().sum()

Days        0
Places      1
Visitors    0
dtype: int64

In [75]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Days      6 non-null      int64
 1   Places    5 non-null      object
 2   Visitors  6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes
None

In [76]:
df.describe()

           Days     Visitors
count  6.000000     6.000000
mean   3.500000  5419.000000
std    1.870829   445.445844
min    1.000000  4890.000000
25%    2.250000  5100.000000
50%    3.500000  5450.000000
75%    4.750000  5575.000000
max    6.000000  6124.000000

In [77]:
df.Places.fillna('BBSR', inplace=True)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_19728\4101320245.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Places.fillna('BBSR', inplace=True)

In [79]:
df.Places = df.Places.fillna('BBSR')
df

   Days    Places  Visitors
0     1      Puri      6124
1     2    Konark      5600
2     3      BBSR      4890
3     4      BBSR      5000
4     5  Rourkela      5400
5     6   Kolkata      5500

In [81]:
df.dtypes

Days         int64
Places      object
Visitors     int64
dtype: object

In [82]:
df.Places.unique()

array(['Puri', 'Konark', 'BBSR', 'Rourkela', 'Kolkata'], dtype=object)

In [83]:
df.Visitors.mean()

np.float64(5419.0)

In [84]:
df.Visitors.std()

445.445844070859

In [85]:
df.Visitors.max()

6124

In [86]:
## 
df.Places[df.Visitors.argmax()]

'Puri'

In [87]:
## it gives you statistical describe on numerical columns
df.describe()

           Days     Visitors
count  6.000000     6.000000
mean   3.500000  5419.000000
std    1.870829   445.445844
min    1.000000  4890.000000
25%    2.250000  5100.000000
50%    3.500000  5450.000000
75%    4.750000  5575.000000
max    6.000000  6124.000000

In [88]:
## including all columns
df.describe(include='all')

            Days Places     Visitors
count   6.000000      6     6.000000
unique       NaN      5          NaN
top          NaN   BBSR          NaN
freq         NaN      2          NaN
mean    3.500000    NaN  5419.000000
std     1.870829    NaN   445.445844
min     1.000000    NaN  4890.000000
25%     2.250000    NaN  5100.000000
50%     3.500000    NaN  5450.000000
75%     4.750000    NaN  5575.000000
max     6.000000    NaN  6124.000000

In [89]:
df.describe(include='O')

       Places
count       6
unique      5
top      BBSR
freq        2