<pre> <h1>Pandas :</h1> is a python library which is used to analyze and manipulate the data, we can read and create datasers using pandas.
    pandas is of two type :
                            -->Series
                            --> DataFrame
     
</pre>

In [1]:
import pandas as pd

In [4]:
## Creating  a Series
# Convert list into Series

s = pd.Series(['a','b','c','d'])
s

0    a
1    b
2    c
3    d
dtype: object

In [5]:
type(s)

pandas.core.series.Series

In [6]:
s[2]

'c'

In [9]:
# Slicing 
s = pd.Series(['a','b','c','d'],index=[10,20,30,40])
s

10    a
20    b
30    c
40    d
dtype: object

In [11]:
# in slicing we can only use orignal index not the updated index
s[1:4:1]

20    b
30    c
40    d
dtype: object

In [12]:
# Tuple to Seies
t = pd.Series((100,200,300,400))
t

0    100
1    200
2    300
3    400
dtype: int64

In [13]:
# Set to series is not possible

In [15]:
# dictionary to Series
d = pd.Series({'a':1, 'b':2 , 'c':3, 'd':4, 'e':5})
d
# it treats the key as index value

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [16]:
d1 = pd.Series({'a':1, 'b':2 , 'c':3, 'd':4, 'e':5},index=['e','f','g','c','a'])
d1

e    5.0
f    NaN
g    NaN
c    3.0
a    1.0
dtype: float64

In [17]:
d['a']

np.int64(1)

In [24]:
## Creating  a DataFrame

d = { 'Name': ['ROHIT', 'MOHIT','RAM','PUROHIT','AMIT','HARI','RAJU'],
       'ROLL' : [20,21,22,23,24,25,26],
        'Course' : ['AI', 'Python', 'C', 'Java', 'C++', 'DA','WD']}
d

{'Name': ['ROHIT', 'MOHIT', 'RAM', 'PUROHIT', 'AMIT', 'HARI', 'RAJU'],
 'ROLL': [20, 21, 22, 23, 24, 25, 26],
 'Course': ['AI', 'Python', 'C', 'Java', 'C++', 'DA', 'WD']}

In [25]:
df = pd.DataFrame(d)
df

      Name  ROLL  Course
0    ROHIT    20      AI
1    MOHIT    21  Python
2      RAM    22       C
3  PUROHIT    23    Java
4     AMIT    24     C++
5     HARI    25      DA
6     RAJU    26      WD

In [27]:
type(df)

pandas.core.frame.DataFrame

In [29]:
df.Name

0      ROHIT
1      MOHIT
2        RAM
3    PUROHIT
4       AMIT
5       HARI
6       RAJU
Name: Name, dtype: object

In [30]:
df.iloc[::,::2]

      Name  Course
0    ROHIT      AI
1    MOHIT  Python
2      RAM       C
3  PUROHIT    Java
4     AMIT     C++
5     HARI      DA
6     RAJU      WD

In [31]:
df.iloc[::2,::]
## Even

    Name  ROLL Course
0  ROHIT    20     AI
2    RAM    22      C
4   AMIT    24    C++
6   RAJU    26     WD

In [32]:
df.iloc[1::2,::]
## odd

      Name  ROLL  Course
1    MOHIT    21  Python
3  PUROHIT    23    Java
5     HARI    25      DA

In [33]:
df.iloc[2]

Name      RAM
ROLL       22
Course      C
Name: 2, dtype: object

In [34]:
df.iloc[::,2]

0        AI
1    Python
2         C
3      Java
4       C++
5        DA
6        WD
Name: Course, dtype: object

In [35]:
df.head()

      Name  ROLL  Course
0    ROHIT    20      AI
1    MOHIT    21  Python
2      RAM    22       C
3  PUROHIT    23    Java
4     AMIT    24     C++

In [36]:
df.tail()

      Name  ROLL Course
2      RAM    22      C
3  PUROHIT    23   Java
4     AMIT    24    C++
5     HARI    25     DA
6     RAJU    26     WD